# Generated by Django 3.1.13 on 2021-11-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='picturecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
