# Generated by Django 3.1.13 on 2021-11-25 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20211121_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
